IF NOT EXISTS (SELECT name FROM sys.tables WHERE name = 'DimShipping')
BEGIN
	CREATE TABLE [dbo].[DimShipping] (
		[ShippingKey] [int] IDENTITY(1,1) NOT NULL, 
		[ShippingID] [int] NOT NULL, 
		[ShippingName] [nvarchar](50) NOT NULL, 
		[ShipBase] [money] NOT NULL, 
		[ShipRate] [money] NOT NULL, 
	CONSTRAINT [PK_DimShipping] PRIMARY KEY CLUSTERED
	(
		[ShippingKey] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]

	CREATE NONCLUSTERED INDEX [NonClusteredIndex-ShippingID] ON [dbo].[DimShipping]
	(
		[ShippingID] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)
END